### ISSUE TITLE
UnicodeDecodeError during installation on Windows platform

### ISSUE THREAD

**Issue by miqbal23** [gbaydin/hypergradient-descent#10]
I'm trying to install this library on my Windows platform thru conda shell, but I receive this error

```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Iqbal\Miniconda3\envs\torch36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Iqbal\\AppData\\Local\\Temp\\pip-req-build-yjo4sm55\\setup.py'"'"'; __file__='"'"'C:\\Users\\Iqbal\\AppData\\Local\\Temp\\pip-req-build-yjo4sm55\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Iqbal\AppData\Local\Temp\pip-req-build-yjo4sm55\pip-egg-info'
         cwd: C:\Users\Iqbal\AppData\Local\Temp\pip-req-build-yjo4sm55\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Iqbal\AppData\Local\Temp\pip-req-build-yjo4sm55\setup.py", line 4, in <module>
        long_description = f.read()
      File "C:\Users\Iqbal\Miniconda3\envs\torch36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5064: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I assume it's because of some special character that's unable being parsed in Windows. Is there any workaround to this?

**Comment by joelters** [comment]
I got the same error, (ChatGPT) solved it by doing the following 

1. Clone the repository locally
`git clone https://github.com/gbaydin/hypergradient-descent.git`
`cd hypergradient-descent`

2. Edit setup.py: Open setup.py and find the line that reads the README file, which likely looks like this:
`with open("README.md") as f:`
and change it to
`with open("README.md", encoding="utf-8") as f:`

3. Install the Package Locally: After saving the changes, try installing the package:
`pip install .`

Then remember to change back the working directory to your original working directory
